import fs from 'node:fs';
const origin=(process.env.SITE_URL || 'https://win123456.github.io/pama_grooming').replace(/\/$/,'');
const pages=[['index','อาบน้ำ ตัดขน ฝากเลี้ยง สุนัขและแมว','PAMA GROOMING บริการอาบน้ำ ตัดขน และฝากเลี้ยงสัตว์เลี้ยง สาขารามคำแหง 114 และพหลโยธิน 64 จองคิวผ่าน LINE'],['services','บริการและราคา','บริการอาบน้ำ ตัดขน ฝากเลี้ยงสุนัขและแมว สอบถามราคาและเงื่อนไขกับ PAMA GROOMING'],['branches','สาขาของเรา','ติดต่อ PAMA GROOMING รามคำแหง 114 และพหลโยธิน 64 พร้อม LINE โทรศัพท์ Facebook และแผนที่ค้นหา'],['gallery','ผลงานของเรา','ติดตามผลงาน Before & After และภาพสัตว์เลี้ยงจากช่องทาง Facebook ของ PAMA GROOMING'],['reviews','รีวิวลูกค้า','ช่องทางดูความคิดเห็นลูกค้า PAMA GROOMING รามคำแหงและพหลโยธิน'],['journal','สาระน่ารู้','บทความเตรียมตัวอาบน้ำตัดขน ดูแลขน และเช็กลิสต์ก่อนฝากเลี้ยงสัตว์เลี้ยง'],['contact','ติดต่อเรา','ติดต่อ PAMA GROOMING รามคำแหง โทร 0612593998 LINE @pamagrooming และพหลโยธิน โทร 0842492255 LINE @pama2'],['prepare-grooming','เตรียมตัวก่อนพาน้องมาอาบน้ำตัดขน','แนวทางเตรียมข้อมูลและจองคิวอาบน้ำตัดขนกับ PAMA GROOMING'],['coat-routine','การดูแลขนสัตว์เลี้ยงที่บ้าน','สร้างกิจวัตรดูแลขนและเลือกอุปกรณ์ให้เหมาะกับสัตว์เลี้ยง'],['boarding-checklist','เช็กลิสต์ก่อนฝากเลี้ยงสัตว์เลี้ยง','เตรียมรายละเอียดกิจวัตร อาหาร และข้อมูลติดต่อก่อนฝากเลี้ยง']];
for(const [slug,title,desc] of pages){fs.writeFileSync(`dist/${slug}.html`,`<!doctype html>\n<html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | PAMA GROOMING</title><meta name="description" content="${desc}"><meta name="theme-color" content="#244E43"><link rel="canonical" href="${origin}/${slug==='index'?'':slug+'.html'}"><meta property="og:title" content="${title} | PAMA GROOMING"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><meta property="og:locale" content="th_TH"><meta property="og:url" content="${origin}/${slug==='index'?'':slug+'.html'}"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script defer src="app.js"></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:'PAMA GROOMING',url:origin,description:pages[0][2],department:[{'@type':'LocalBusiness',name:'PAMA GROOMING รามคำแหง 114',telephone:'+66612593998'},{'@type':'LocalBusiness',name:'PAMA GROOMING พหลโยธิน 64',telephone:'+66842492255'}]})}</script></head><body><div id="app"></div><noscript><main><h1>PAMA GROOMING</h1><p>อาบน้ำ ตัดขน ฝากเลี้ยง สุนัขและแมว</p><p>สาขารามคำแหง 114 <a href="https://lin.ee/pBC80S0">LINE @pamagrooming</a> โทร <a href="tel:0612593998">0612593998</a></p><p>สาขาพหลโยธิน 64 <a href="https://lin.ee/Pa2GWJz">LINE @pama2</a> โทร <a href="tel:0842492255">0842492255</a></p><p>กรุณาเปิด JavaScript เพื่อดูเว็บไซต์ฉบับเต็ม</p></main></noscript></body></html>`)}
fs.writeFileSync('dist/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#244E43"/><text x="32" y="46" text-anchor="middle" font-family="sans-serif" font-size="44" fill="#F8F5EE">P</text></svg>');
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(p=>`<url><loc>${origin}/${p[0]==='index'?'':p[0]+'.html'}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
if(fs.existsSync('.openai/hosting.json')){const manifest=JSON.parse(fs.readFileSync('.openai/hosting.json','utf8'));manifest.static={directory:'dist'};fs.writeFileSync('.openai/hosting.json',JSON.stringify(manifest,null,2)+'\n');}
console.log(`Generated ${pages.length} pages, sitemap and static hosting manifest.`);
