import {WeightInput} from './weight-input';
import {defineArrayMember,defineField,defineType} from 'sanity';
import {defaultContact,defaultServices,defaultGallery} from '@/lib/cms-defaults';
const heading=[defineField({name:'title',title:'หัวข้อหน้า',type:'string',validation:r=>r.required()}),defineField({name:'description',title:'คำอธิบายหน้า',type:'text',rows:3,validation:r=>r.required()}),defineField({name:'eyebrow',title:'ข้อความเล็กเหนือหัวข้อ',type:'string'})];
const url=(name:string,title:string,relative=false)=>defineField({name,title,type:'url',validation:r=>r.uri({scheme:['https'],allowRelative:relative})});
const image=(name:string,title:string)=>defineField({name,title,type:'image',options:{hotspot:true},fields:[defineField({name:'alt',title:'คำอธิบายภาพ',type:'string'})]});
export const serviceSeed={...defaultServices,services:defaultServices.services.map(({image,...s})=>({...s,imageUrl:image}))};
export const serviceSettings=defineType({name:'serviceSettings',title:'บริการและราคา',type:'document',initialValue:serviceSeed,fields:[...heading,defineField({name:'ratesImported',title:'นำเข้าราคาจริงแล้ว',type:'boolean',hidden:true,readOnly:true}),
 defineField({name:'services',title:'รายการบริการ',type:'array',of:[defineArrayMember({type:'object',name:'serviceItem',fields:[defineField({name:'number',title:'ลำดับที่แสดง เช่น 01',type:'string'}),defineField({name:'title',title:'ชื่อบริการ',type:'string',validation:r=>r.required()}),defineField({name:'label',title:'ชื่อภาษาอังกฤษ',type:'string'}),defineField({name:'description',title:'รายละเอียด',type:'text',rows:3,validation:r=>r.required()}),image('image','รูปบริการ'),url('imageUrl','ลิงก์รูปสำรอง',true)],validation:r=>r.custom(v=>v?.image||v?.imageUrl?true:'เพิ่มรูปบริการหรือลิงก์รูป'),preview:{select:{title:'title',media:'image'}}})]}),
 defineField({name:'prices',title:'รายการราคา',description:'ใส่ราคา เช่น เริ่มต้น 350 บาท หรือ สอบถามผ่าน LINE',type:'array',of:[defineArrayMember({name:'priceItem',type:'object',fields:[defineField({name:'pet',title:'สัตว์เลี้ยง',type:'string',options:{list:['สุนัข','แมว']},validation:r=>r.required()}),defineField({name:'weight',title:'ขนาด / ช่วงน้ำหนัก',type:'string',description:'เลือกสัตว์เลี้ยงก่อน เพื่อแสดงช่วงน้ำหนักที่ตรงกัน',components:{input:WeightInput}}),defineField({name:'coat',title:'ประเภทขน',type:'string',options:{list:['ขนสั้น','ขนยาว','ขนพิเศษ / ขนหนา','ทุกประเภทขน']}}),defineField({name:'service',title:'บริการ / ช่วงน้ำหนัก',type:'string',validation:r=>r.required()}),defineField({name:'price',title:'ราคาที่แสดง',type:'string',description:'เช่น เริ่มต้น 350 บาท แก้เป็นราคาจริงแล้วปิดสถานะราคาตัวอย่างด้านล่าง',validation:r=>r.required()}),defineField({name:'example',title:'เป็นราคาตัวอย่าง (ยังไม่ใช่ราคาจริง)',type:'boolean',initialValue:false})],preview:{select:{title:'service',subtitle:'price'}}})]}),
 defineField({name:'homeFaqs',title:'FAQ หน้าแรก',description:'เพิ่ม ลบ เรียงคำถามได้ แนะนำประมาณ 6 ข้อ',type:'array',initialValue:defaultServices.homeFaqs,of:[defineArrayMember({type:'object',name:'homeFaq',fields:[defineField({name:'question',title:'คำถาม',type:'string',validation:r=>r.required()}),defineField({name:'answer',title:'คำตอบ',type:'text',validation:r=>r.required()})],preview:{select:{title:'question'}}})]}),
 defineField({name:'faqs',title:'คำถามก่อนจองบริการ',type:'array',of:[defineArrayMember({type:'object',name:'serviceFaq',fields:[defineField({name:'question',title:'คำถาม',type:'string',validation:r=>r.required()}),defineField({name:'answer',title:'คำตอบ',type:'text',validation:r=>r.required()})],preview:{select:{title:'question'}}})]}),
 defineField({name:'priceNote',title:'หมายเหตุใต้ตารางราคา',type:'text',rows:3}),defineField({name:'imageNote',title:'หมายเหตุภาพบริการ (ลบเมื่อใช้ภาพร้านจริง)',type:'string'})]});
export const gallerySettings=defineType({name:'gallerySettings',title:'ผลงานของเรา',type:'document',initialValue:defaultGallery,fields:[...heading,defineField({name:'works',title:'ผลงาน Before & After',description:'เพิ่ม ลบ หรือลากเพื่อเรียงลำดับ รูป After จะเป็นพื้นหลังด้วย',type:'array',of:[defineArrayMember({name:'workItem',type:'object',fields:[defineField({name:'title',title:'ชื่อผลงาน / ชื่อน้อง',type:'string',validation:r=>r.required()}),defineField({name:'breed',title:'สายพันธุ์ / ป้ายบนรูป',type:'string',validation:r=>r.required()}),defineField({name:'style',title:'คำบรรยายใต้ภาพ',type:'string'}),image('before','ภาพก่อนทำ'),url('beforeUrl','ลิงก์ภาพก่อนทำสำรอง',true),image('after','ภาพหลังทำ'),url('afterUrl','ลิงก์ภาพหลังทำสำรอง',true),defineField({name:'illustration',title:'เป็นภาพประกอบ',type:'boolean',initialValue:false,description:'ปิดเมื่อใช้ภาพผลงานจริงของร้าน'}),defineField({name:'tone',title:'โทนกรอบ',type:'string',initialValue:'mint',options:{list:[{title:'เขียว',value:'mint'},{title:'พีช',value:'peach'},{title:'ฟ้า',value:'blue'}]}})],validation:r=>r.custom(v=> (v?.before||v?.beforeUrl)&&(v?.after||v?.afterUrl)?true:'เพิ่มภาพ Before และ After ให้ครบ'),preview:{select:{title:'title',subtitle:'breed',media:'after'}}})]})]});
export const contactSettings=defineType({name:'contactSettings',title:'ติดต่อเราและสาขา',type:'document',initialValue:defaultContact,fields:[...heading,defineField({name:'branches',title:'สาขาและช่องทางติดต่อ',description:'ข้อมูลใช้ร่วมกันในหน้าติดต่อ สาขา ปุ่มจองคิว และท้ายเว็บ',type:'array',of:[defineArrayMember({name:'branchItem',type:'object',fields:[defineField({name:'name',title:'ชื่อสาขา',type:'string',validation:r=>r.required()}),defineField({name:'address',title:'ที่อยู่',type:'text',rows:2}),defineField({name:'hours',title:'วันและเวลาเปิด–ปิด',type:'string'}),defineField({name:'offersBoarding',title:'มีบริการฝากเลี้ยง',type:'boolean',initialValue:false}),defineField({name:'phone',title:'เบอร์โทรสำหรับลิงก์โทร (ตัวเลข)',type:'string',validation:r=>r.required().regex(/^\+?[0-9]{8,15}$/)}),defineField({name:'display',title:'เบอร์โทรที่แสดง เช่น 061-259-3998',type:'string',validation:r=>r.required()}),defineField({name:'line',title:'LINE ID',type:'string',validation:r=>r.required()}),defineField({...url('url','ลิงก์จองคิว LINE'),validation:r=>r.required().uri({scheme:['https']})}),url('fb','ลิงก์ Facebook'),url('mapUrl','ลิงก์หมุด Google Maps'),defineField({...url('mapEmbedUrl','ลิงก์แผนที่ฝัง (Embed)'),description:'ใช้ https://www.google.com/maps/embed?... หรือ https://maps.google.com/maps?...',validation:r=>r.custom(v=>{if(!v)return true;try{const u=new URL(v);return u.protocol==='https:'&&['www.google.com','maps.google.com'].includes(u.hostname)&&u.pathname.startsWith('/maps')?true:'ใช้ลิงก์แผนที่ Google แบบ HTTPS เท่านั้น'}catch{return 'ลิงก์ไม่ถูกต้อง'}})})],preview:{select:{title:'name',subtitle:'display'}}})]})]});
