import {branches, services, pageInfo} from './content';
import {confirmedPrices,confirmedPriceNote,defaultHomeFaqs} from './service-rates';
export type Branch = {name:string;line:string;url:string;phone:string;display:string;fb:string;address?:string;hours?:string;mapUrl?:string;mapEmbedUrl?:string;offersBoarding?:boolean};
export function branchOffersBoarding(branch:Branch) {
 return branch.offersBoarding ?? branch.name.includes('พหลโยธิน');
}
export type Service = {number:string;title:string;description:string;image:string;label:string;imageAlt?:string};
export type Price = {_key:string;pet:'สุนัข'|'แมว';service:string;price:string;weight?:string;coat?:string;example?:boolean};
export type Work = {_key:string;breed:string;title:string;style:string;tone:string;beforeUrl:string;afterUrl:string;illustration:boolean};
export const defaultContact = {_id:'pama-contact-settings',_type:'contactSettings',...pageInfo.contact,branches:branches.map((b,i)=>({...b,_key:`branch-${i}`,offersBoarding:i===1,mapUrl:`https://www.google.com/maps?cid=${i===0?'6028078088449819595':'16215279692386569272'}&hl=th`,mapEmbedUrl:`https://maps.google.com/maps?q=${i===0?'13.778845,100.677775':'13.945743,100.623522'}&z=16&output=embed`,hours:'กรุณาสอบถามสาขาผ่าน LINE'}))};
export const defaultServices = {_id:'pama-service-settings',_type:'serviceSettings',...pageInfo.services,services:services.map((s,i)=>({...s,_key:`service-${i}`})),ratesImported:true,prices:confirmedPrices,homeFaqs:defaultHomeFaqs,faqs:[{_key:'price',question:'ราคาและเงื่อนไขบริการ',answer:'สอบถามราคา รายการบริการที่รวมอยู่ และค่าใช้จ่ายเพิ่มเติมกับสาขาโดยตรง แจ้งลักษณะขน ขนพันกัน และข้อจำกัดในการดูแลก่อนจอง เพื่อให้ร้านประเมินรายละเอียดได้'},{_key:'booking',question:'จองคิวอย่างไร?',answer:'เลือกสาขา ทัก LINE OA แจ้งบริการและวันที่ต้องการ จากนั้นรอร้านยืนยันคิวและราคา การเปิดแชตยังไม่ถือเป็นการยืนยันการจอง'},{_key:'boarding',question:'ต้องเตรียมอะไรสำหรับฝากเลี้ยง?',answer:'แจ้งวันเข้าพัก วันรับกลับ และกิจวัตรของน้อง สอบถามเงื่อนไข เอกสาร อาหารและของใช้ที่ต้องนำมาจากสาขาก่อนเข้าพัก'}],priceNote:confirmedPriceNote,imageNote:'ภาพประกอบบรรยากาศ ไม่ใช่ภาพผลงานของร้าน'};
export const defaultGallery = {_id:'pama-gallery-settings',_type:'gallerySettings',...pageInfo.gallery,works:[{id:'pomeranian',breed:'Pomeranian',title:'ปอมเมอเรเนียน',style:'ดูแลขนให้เป็นทรงนุ่มฟู',tone:'mint'},{id:'poodle',breed:'Poodle',title:'พุดเดิล',style:'ทรงเท็ดดี้แบร์ ดูแลง่าย',tone:'peach'},{id:'schnauzer',breed:'Schnauzer',title:'ชเนาเซอร์',style:'เก็บทรง คงเอกลักษณ์ของน้อง',tone:'blue'}].map(({id,...w})=>({...w,_key:id,beforeUrl:`/images/works/${id}-before.webp`,afterUrl:`/images/works/${id}-after.webp`,illustration:true}))};
