export const homeFieldTitles={
  "heroBadge": "ข้อความเล็กบนแบนเนอร์",
  "heroTitle": "หัวข้อแบนเนอร์",
  "heroDescription": "คำอธิบายแบนเนอร์",
  "heroNote": "ข้อความใต้ปุ่ม",
  "stamp": "ข้อความตราบนรูป",
  "floatTitle": "ข้อความบนกรอบลอย",
  "floatDescription": "ข้อความรองกรอบลอย",
  "exploreLabel": "ข้อความปุ่มบริการ",
  "strip0": "ข้อความแถบบริการ 1",
  "strip1": "ข้อความแถบบริการ 2",
  "strip2": "ข้อความแถบบริการ 3",
  "strip3": "ข้อความแถบบริการ 4",
  "storyEyebrow": "ข้อความเล็กแนะนำร้าน",
  "storyTitle": "หัวข้อแนะนำร้าน",
  "storyDescription": "รายละเอียดแนะนำร้าน",
  "pointTitle0": "หัวข้อจุดเด่น 1",
  "pointTitle1": "หัวข้อจุดเด่น 2",
  "pointTitle2": "หัวข้อจุดเด่น 3",
  "pointTitle3": "หัวข้อจุดเด่น 4",
  "pointDescription0": "คำอธิบายจุดเด่น 1",
  "pointDescription1": "คำอธิบายจุดเด่น 2",
  "pointDescription2": "คำอธิบายจุดเด่น 3",
  "pointDescription3": "คำอธิบายจุดเด่น 4",
  "sectionEyebrow0": "ข้อความเล็กส่วน ทุกการดูแล เพื่อเพื่อนตัวโปรด",
  "sectionTitle0": "หัวข้อส่วน ทุกการดูแล เพื่อเพื่อนตัวโปรด",
  "sectionEyebrow1": "ข้อความเล็กส่วน ใกล้บ้านคุณ ใกล้ใจน้อง",
  "sectionTitle1": "หัวข้อส่วน ใกล้บ้านคุณ ใกล้ใจน้อง",
  "sectionEyebrow2": "ข้อความเล็กส่วน ความน่ารักที่อยากแบ่งปัน",
  "sectionTitle2": "หัวข้อส่วน ความน่ารักที่อยากแบ่งปัน",
  "sectionEyebrow3": "ข้อความเล็กส่วน เสียงจากครอบครัวของน้อง",
  "sectionTitle3": "หัวข้อส่วน เสียงจากครอบครัวของน้อง",
  "sectionEyebrow4": "ข้อความเล็กส่วน เรื่องเล็ก ๆ เพื่อการดูแลที่ดี",
  "sectionTitle4": "หัวข้อส่วน เรื่องเล็ก ๆ เพื่อการดูแลที่ดี",
  "branchesDescription": "คำอธิบายส่วนสาขา",
  "sectionLink0": "ข้อความลิงก์ส่วน 1",
  "sectionLink1": "ข้อความลิงก์ส่วน 2",
  "sectionLink2": "ข้อความลิงก์ส่วน 3",
  "sectionLink3": "ข้อความลิงก์ส่วน 4",
  "heroImageUrl": "ลิงก์รูปแบนเนอร์",
  "heroImageAlt": "คำอธิบายรูปแบนเนอร์",
  "storyImageUrl": "ลิงก์รูปแนะนำร้าน",
  "storyImageAlt": "คำอธิบายรูปแนะนำร้าน",
  "ctaTitle": "หัวข้อจองคิวท้ายหน้า",
  "ctaDescription": "คำอธิบายจองคิวท้ายหน้า",
  "faqTitle": "หัวข้อ FAQ",
  "faqEyebrow": "ข้อความเล็ก FAQ",
  "faqLink": "ข้อความลิงก์ FAQ"
} as const;
export const defaultHome={
  "heroBadge": "A LITTLE CARE. A LOT OF LOVE.",
  "heroTitle": "ดูแลด้วยใจ\nให้ทุกวันของน้อง\nเป็นวันที่ดี",
  "heroDescription": "PAMA GROOMING บริการอาบน้ำ ตัดขน และฝากเลี้ยง\nสำหรับน้องหมาน้องแมว เพราะเพื่อนตัวเล็กของคุณ\nควรได้รับช่วงเวลาดี ๆ ในทุกครั้งที่มาเจอกัน",
  "heroNote": "ต้อนรับน้องหมาและน้องแมว · 2 สาขาในกรุงเทพฯ",
  "stamp": "LITTLE PAWS\nBIG LOVE\n♡",
  "floatTitle": "ความสุข เริ่มจากการดูแล",
  "floatDescription": "Bath · Grooming · Boarding",
  "exploreLabel": "สำรวจบริการ",
  "strip0": "อาบน้ำ & ดูแลขน",
  "strip1": "ตัดขน & จัดทรง",
  "strip2": "ฝากเลี้ยง · พหลโยธิน 64",
  "strip3": "รามคำแหง 114 · พหลโยธิน 64",
  "storyEyebrow": "HELLO, WE ARE PAMA",
  "storyTitle": "เพราะน้องคือครอบครัว\nการดูแลจึงมีความหมาย",
  "storyDescription": "จากวันอาบน้ำ ไปจนถึงวันฝากเลี้ยง PAMA เป็นอีกหนึ่งจุดหมายสำหรับการดูแลเพื่อนสี่ขา เลือกบริการและพูดคุยกับสาขาที่สะดวก เพื่อเตรียมการดูแลให้เหมาะกับน้องของคุณ",
  "pointTitle0": "ครบทั้ง 3 บริการ",
  "pointTitle1": "เลือกได้ 2 สาขา",
  "pointTitle2": "พูดคุยก่อนจอง",
  "pointTitle3": "สำหรับหมาและแมว",
  "pointDescription0": "อาบน้ำ ตัดขน และฝากเลี้ยง",
  "pointDescription1": "รามคำแหงและพหลโยธิน",
  "pointDescription2": "แจ้งรายละเอียดผ่าน LINE OA",
  "pointDescription3": "สอบถามบริการที่เหมาะกับน้อง",
  "sectionEyebrow0": "OUR SERVICES",
  "sectionTitle0": "ทุกการดูแล เพื่อเพื่อนตัวโปรด",
  "sectionEyebrow1": "FIND YOUR PAMA",
  "sectionTitle1": "ใกล้บ้านคุณ ใกล้ใจน้อง",
  "sectionEyebrow2": "OUR LITTLE FRIENDS",
  "sectionTitle2": "ความน่ารักที่อยากแบ่งปัน",
  "sectionEyebrow3": "FROM OUR CUSTOMERS",
  "sectionTitle3": "เสียงจากครอบครัวของน้อง",
  "sectionEyebrow4": "THE PAMA JOURNAL",
  "sectionTitle4": "เรื่องเล็ก ๆ เพื่อการดูแลที่ดี",
  "branchesDescription": "เลือกสาขาที่สะดวก แล้วให้เราเป็นส่วนหนึ่ง\nของวันดี ๆ ของเพื่อนตัวเล็ก",
  "sectionLink0": "บริการและราคาทั้งหมด ↗",
  "sectionLink1": "ชมผลงานของเรา ↗",
  "sectionLink2": "ดูช่องทางรีวิว ↗",
  "sectionLink3": "อ่านสาระน่ารู้ ↗",
  "heroImageUrl": "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1000&q=85",
  "heroImageAlt": "สุนัขโกลเด้นรีทรีฟเวอร์",
  "storyImageUrl": "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=700&q=85",
  "storyImageAlt": "สุนัขสองตัว",
  "ctaTitle": "นัดวันดูแล ให้เจ้าตัวโปรด",
  "ctaDescription": "เลือกสาขาที่สะดวก แล้วทัก LINE เพื่อสอบถามราคาและคิวว่าง",
  "faqTitle": "คำถามที่พบบ่อยเกี่ยวกับ PAMA GROOMING (FAQ)",
  "faqEyebrow": "GOOD TO KNOW",
  "faqLink": "สอบถามเพิ่มเติม ↗"
};
export type HomeContent=typeof defaultHome;
export const homeSeed={_id:'pama-home-settings',_type:'homeSettings',...defaultHome};
